input.buttonB.onEvent(ButtonEvent.Down, function () {
    light.setAll(0xff0000)
    music.powerDown.play()
    crickit.motor1.stop()
    crickit.motor2.stop()
})
input.buttonA.onEvent(ButtonEvent.Up, function () {
    light.setAll(0x00ff00)
    music.powerUp.play()
    crickit.motor1.setInverted(true)
    crickit.motor2.setInverted(true)
    crickit.motor1.run(50)
    crickit.motor2.run(50)
})
input.onGesture(Gesture.Shake, function () {
    light.setAll(0x7f00ff)
    pause(200)
    crickit.motor1.stop()
    crickit.motor2.stop()
    crickit.motor1.setInverted(false)
    crickit.motor2.setInverted(false)
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    pause(200)
    crickit.motor1.run(50)
    crickit.motor2.run(50)
    pause(200)
    crickit.motor1.setInverted(true)
    crickit.motor2.setInverted(true)
    pause(200)
    crickit.motor1.stop()
    crickit.motor2.run(80)
    pause(500)
    crickit.motor2.stop()
    pause(200)
    light.setAll(0x00ff00)
    crickit.motor2.run(50)
    crickit.motor1.run(50)
})
music.setVolume(50)
music.magicWand.play()
light.showAnimation(light.cometAnimation, 5000)
